INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('001', 1, 'Lakban', 'Buah', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('002', 1, 'Sarung tangan plastik', 'Pack', 3);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('003', 1, 'Sarung Tangan Kain', 'Pack', 3);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('004', 1, 'Tab Dispenser', 'Buah', 2);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('005', 1, 'Buku Pembukuan', 'Buah', 2);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('006', 1, 'Sabun Ekonomi', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('007', 1, 'Wipol', 'Bungkus', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('008', 1, 'Tabung gas', 'Tabung', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('009', 1, 'Sunlight', 'Bungkus', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('010', 1, 'Kertas nasi', 'Ikat', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('011', 2, 'Kotak Nasi', 'Karung', 3);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('012', 2, 'Set Alat Makan', 'Pack', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('013', 2, 'Cup 25ml', 'Dus', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('014', 2, 'Kotak Kue', 'Karung', 3);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('015', 3, 'Beras', 'Karung', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('016', 3, 'Kerupuk', 'Bal', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('017', 3, 'Garam', 'Pack', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('018', 3, 'Peksin', 'Bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('019', 3, 'Gula Putih', 'Kilo', 15);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('020', 3, 'Kecap Manis', 'Bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('021', 3, 'Saos Tomat', 'Bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('022', 3, 'Saos tiram', 'Bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('023', 3, 'Terasi', 'Bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('024', 3, 'Tepung', 'Kilo', 20);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('025', 3, 'Telur', 'Piring', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('026', 3, 'Minyak Goreng', 'Dirigen', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('027', 3, 'Mihun', 'Bungkus', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('028', 3, 'Bawang Merah', 'Kilo', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('029', 3, 'Bawang Putih ', 'Kilo', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('030', 3, 'Kemiri', 'Kilo', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('031', 3, 'Kunyit', 'Ons', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('032', 3, 'Jahe', 'Ons', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('033', 3, 'Lengkuas', 'Ons', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('034', 3, 'Sereh', 'ons', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('035', 3, 'Tempe', 'Papan', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('036', 3, 'Lombok Kering', 'Kilo', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('037', 3, 'Tahu', 'Dirigen', 2);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('038', 3, 'Gula Merah', 'Kilo', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('039', 3, 'ketumbar', 'Kilo', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('040', 3, 'Lada Hitam', 'Kilo', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('041', 3, 'Bawang Bombai', 'Kilo', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('042', 3, 'sasa', 'bungkus', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('043', 3, 'Asam jawa', 'Pack', 10);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('044', 4, 'Air Mineral', 'Dus', 20);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('045', 4, 'Teh Kotak', 'Dus ', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('046', 5, 'Plastik Warna', 'Ikat', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('047', 5, 'Plastik 35', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('048', 5, 'Plastik 20', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('049', 5, 'Plastik 15', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('050', 5, 'Plastik 13', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('051', 5, 'Plastik 11', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('052', 5, 'Plastik 9', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('053', 5, 'Plastik 7', 'Pack', 5);
INSERT INTO inventory_items (code, inventory_category_id, name, unit, low_quantity) VALUES ('054', 5, 'Plastik Sampah', 'Pack', 5);